service: jupitor

plugins:
    - serverless-bundle
    - serverless-aws-alias

provider:
    name: aws
    runtime: nodejs12.x
    region: us-east-1
    tracing:
        apiGateway: true
        lambda: true
    timeout: 30
    aliasStage:
        loggingLevel: 'ERROR'
        dataTraceEnabled: true
    environment:
        COGNITO_USER_POOL_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolId}
        COGNITO_CLIENT_ID: ${file(../../resources/stack-outputs/cognito-${self:custom.stage}.yml):CognitoUserPoolClientId}
        STAGE: ${self:custom.stage}
        DB_RESOURCE_ARN: ${file(../../resources/stack-outputs/database-${self:custom.stage}.yml):DbClusterArn}
        SECRET_ARN: ${file(../../resources/stack-outputs/database-${self:custom.stage}.yml):SecretManagerArn}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - rds-data:ExecuteStatement
              - rds-data:BatchExecuteStatement
              - rds-data:BeginTransaction
              - rds-data:CommitTransaction
              - rds-data:RollbackTransaction
          Resource: '*'
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource:
              'Fn::ImportValue': ${self:custom.stage}-SecretManagerArn

custom:
    defaultStage: ${file(../../../serverless.common.yml):custom.defaultStage}
    resourcesStages: ${file(../../../serverless.common.yml):custom.resourcesStages}
    resourceStage: ${file(../../../serverless.common.yml):custom.resourcesStage}
    stage: ${file(../../../serverless.common.yml):custom.stage}
    baseApiPath: ${file(../../../serverless.common.yml):custom.baseApiPath}
    alias: ${file(../../../serverless.common.yml):custom.alias}
    jupitorEntityPath: ${self:custom.baseApiPath}/jupitor

    bundle:
        forceExclude:
            - datman-helpers
            - datman-models
        linting: false #Ignore for compilation
        ignorePackages:
            - pg-hstore
            # only on aws
            - ../../../layers/helper_lib/src
            - ../../../layers/models_lib/src
            - ../../../../layers/helper_lib/src
            - ../../../../layers/models_lib/src

functions:
    - ${file(functions.yml)}
resources:
    # API Gateway Errors
    - ${file(api-gateway-errors.yml)}
